<?xml version="1.0"?>
<package format="3">
  <name>rpk</name>
  <version>5.7.0</version>
  <description>A tool to create and package ROS 2 robot applications</description>
  <maintainer email="severin.lemaignan@pal-robotics.com">Séverin Lemaignan</maintainer>
  <license>Apache License 2.0</license>

  <exec_depend>python3-jinja2</exec_depend>

  <!-- ################################################### -->
  <!-- Tests dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>python3-pytest</test_depend>

  <!--
  Tests include trying to compile all the templates.
  As such, all the dependencies of the templates must be installed.
  -->

  <test_depend>action_msgs</test_depend>
  <test_depend>ament_cmake</test_depend>
  <test_depend>ament_cmake_auto</test_depend>
  <test_depend>ament_index_python</test_depend>
  <test_depend>diagnostic_msgs</test_depend>
  <test_depend>diagnostic_updater</test_depend>
  <test_depend>hri_actions_msgs</test_depend>
  <test_depend>kb_msgs</test_depend>
  <test_depend>launch</test_depend>
  <test_depend>launch_pal</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>lifecycle_msgs</test_depend>
  <test_depend>nlohmann-json-dev</test_depend>
  <test_depend>pyhri</test_depend>
  <test_depend>rclcpp</test_depend>
  <test_depend>rclcpp_action</test_depend>
  <test_depend>rclcpp_lifecycle</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>rosidl_default_generators</test_depend>
  <test_depend>std_skills</test_depend>
  <test_depend>ament_archlint</test_depend>
  <!-- ################################################### -->

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
